#!/bin/bash
##===----------------------------------------------------------------------===##
##
## This source file is part of the SwiftNIO open source project
##
## Copyright (c) 2021 Apple Inc. and the SwiftNIO project authors
## Licensed under Apache License v2.0
##
## See LICENSE.txt for license information
## See CONTRIBUTORS.txt for the list of SwiftNIO project authors
##
## SPDX-License-Identifier: Apache-2.0
##
##===----------------------------------------------------------------------===##

set -eu
set -o pipefail

here="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

url_prefix=${1-"https://ci.swiftserver.group/job/swift-nio-http2-2-"}
target_repo=${2-"$here/.."}
tmpdir=$(mktemp -d /tmp/.last-build_XXXXXX)

for f in swift56 swift57 swift58 swift59 nightly; do
    echo "$f"
    url="$url_prefix$f-prb/lastCompletedBuild/consoleFull"
    stripped=${f#"swift"}
    echo "$url"
    curl -s "$url" | "$here/alloc-limits-from-test-output" > "$tmpdir/limits$stripped"

    if [[ "$(wc -l < "$tmpdir/limits$stripped")" -lt 5 ]]; then
        echo >&2 "ERROR: fewer than 5 limits found, something's not right"
        exit 1
    fi


    docker_file=$(if [[ "$stripped" == "nightly" ]]; then stripped=main; fi && ls "$target_repo/docker/docker-compose."*"$stripped"*".yaml")

    echo "$docker_file"
    cat "$tmpdir/limits$stripped"
    cat "$docker_file" | grep -v MAX_ALLOCS_ALLOWED | grep -B10000 "^    environment:" > "$tmpdir/pre$stripped"
    cat "$docker_file" | grep -v MAX_ALLOCS_ALLOWED | grep -A10000 "^    environment:" | sed 1d > "$tmpdir/post$stripped"
    cat "$tmpdir/pre$stripped" "$tmpdir/limits$stripped" "$tmpdir/post$stripped" > "$docker_file"
done

rm -rf "$tmpdir"
