//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// ConnectionStateMachineTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension ConnectionStateMachineTests {

   @available(*, deprecated, message: "not actually deprecated. Just deprecated to allow deprecated tests (which test deprecated functionality) without warnings")
   static var allTests : [(String, (ConnectionStateMachineTests) -> () throws -> Void)] {
      return [
                ("testSimpleRequestResponseFlow", testSimpleRequestResponseFlow),
                ("testSimpleRequestResponseErrorFlow", testSimpleRequestResponseErrorFlow),
                ("testOpeningConnectionWhileServerPreambleMissing", testOpeningConnectionWhileServerPreambleMissing),
                ("testServerSendsItsPreambleFirst", testServerSendsItsPreambleFirst),
                ("testMoreComplexStreamLifecycle", testMoreComplexStreamLifecycle),
                ("testServerCannotInitiateStreamsWithHeaders", testServerCannotInitiateStreamsWithHeaders),
                ("testSimpleServerPush", testSimpleServerPush),
                ("testSimpleStreamResetFlow", testSimpleStreamResetFlow),
                ("testHeadersOnClosedStreamAfterServerGoaway", testHeadersOnClosedStreamAfterServerGoaway),
                ("testDataOnClosedStreamAfterServerGoaway", testDataOnClosedStreamAfterServerGoaway),
                ("testWindowUpdateOnClosedStreamAfterServerGoaway", testWindowUpdateOnClosedStreamAfterServerGoaway),
                ("testRstStreamOnClosedStreamAfterServerGoaway", testRstStreamOnClosedStreamAfterServerGoaway),
                ("testPushesAfterServerGoaway", testPushesAfterServerGoaway),
                ("testClientMayNotInitiateNewStreamAfterServerGoaway", testClientMayNotInitiateNewStreamAfterServerGoaway),
                ("testHeadersOnClosedStreamAfterClientGoaway", testHeadersOnClosedStreamAfterClientGoaway),
                ("testDataOnClosedStreamAfterClientGoaway", testDataOnClosedStreamAfterClientGoaway),
                ("testWindowUpdateOnClosedStreamAfterClientGoaway", testWindowUpdateOnClosedStreamAfterClientGoaway),
                ("testRstStreamOnClosedStreamAfterClientGoaway", testRstStreamOnClosedStreamAfterClientGoaway),
                ("testServerMayNotInitiateNewStreamAfterClientGoaway", testServerMayNotInitiateNewStreamAfterClientGoaway),
                ("testSendingFramesBeforePrefaceIsIllegal", testSendingFramesBeforePrefaceIsIllegal),
                ("testSendingFramesBeforePrefaceAfterReceivedPrefaceIsIllegal", testSendingFramesBeforePrefaceAfterReceivedPrefaceIsIllegal),
                ("testSendingFramesBeforePrefaceAfterReceivedPrefaceAndGoawayIsIllegal", testSendingFramesBeforePrefaceAfterReceivedPrefaceAndGoawayIsIllegal),
                ("testReceivingFramesBeforePrefaceIsIllegal", testReceivingFramesBeforePrefaceIsIllegal),
                ("testReceivingFramesBeforePrefaceAfterSentPrefaceIsIllegal", testReceivingFramesBeforePrefaceAfterSentPrefaceIsIllegal),
                ("testReceivingFramesBeforePrefaceAfterSentPrefaceAndGoawayIsIllegal", testReceivingFramesBeforePrefaceAfterSentPrefaceAndGoawayIsIllegal),
                ("testRatchetingGoaway", testRatchetingGoaway),
                ("testRatchetingGoawayForBothPeers", testRatchetingGoawayForBothPeers),
                ("testInvalidGoawayFrames", testInvalidGoawayFrames),
                ("testCanSendRequestsWithoutReceivingPreface", testCanSendRequestsWithoutReceivingPreface),
                ("testCanQuiesceAndSendRequestsWithoutReceivingPreface", testCanQuiesceAndSendRequestsWithoutReceivingPreface),
                ("testFullyQuiescedConnection", testFullyQuiescedConnection),
                ("testImplicitConnectionCompletion", testImplicitConnectionCompletion),
                ("testClosedStreamsForbidAllActivity", testClosedStreamsForbidAllActivity),
                ("testPushesAfterSendingPrefaceAreInvalid", testPushesAfterSendingPrefaceAreInvalid),
                ("testClientsMayNotPush", testClientsMayNotPush),
                ("testMaySendSettingsInAllStates", testMaySendSettingsInAllStates),
                ("testValidatingFlowControlOnFullyActiveConnections", testValidatingFlowControlOnFullyActiveConnections),
                ("testTrailersWithoutData", testTrailersWithoutData),
                ("testServerResponseEndsBeforeRequestFinishes", testServerResponseEndsBeforeRequestFinishes),
                ("testPushedResponsesMayHaveBodies", testPushedResponsesMayHaveBodies),
                ("testDataFramesWithoutEndStream", testDataFramesWithoutEndStream),
                ("testSendingCompleteRequestBeforeResponse", testSendingCompleteRequestBeforeResponse),
                ("testWindowUpdateValidity", testWindowUpdateValidity),
                ("testWindowUpdateOnClosedStream", testWindowUpdateOnClosedStream),
                ("testWindowIncrementsOfSizeZeroArentOk", testWindowIncrementsOfSizeZeroArentOk),
                ("testCannotSendDataFrames", testCannotSendDataFrames),
                ("testChangingInitialWindowSizeLotsOfStreams", testChangingInitialWindowSizeLotsOfStreams),
                ("testTooManyHeadersArentOk", testTooManyHeadersArentOk),
                ("testInvalidChangesToConnectionFlowControlWindow", testInvalidChangesToConnectionFlowControlWindow),
                ("testSettingsACKWithoutOutstandingSettingsIsAnError", testSettingsACKWithoutOutstandingSettingsIsAnError),
                ("testClientsMustCreateStreamsWithOddStreamIDs", testClientsMustCreateStreamsWithOddStreamIDs),
                ("testClientsServersMayNotCreateStreamsBackwards", testClientsServersMayNotCreateStreamsBackwards),
                ("testUnknownSettingsAreIgnored", testUnknownSettingsAreIgnored),
                ("testMaxConcurrentStreamsEnforcement", testMaxConcurrentStreamsEnforcement),
                ("testDisablingPushPreventsPush", testDisablingPushPreventsPush),
                ("testRatchetingGoawayEvenWhenFullyQueisced", testRatchetingGoawayEvenWhenFullyQueisced),
                ("testRatchetingGoawayForBothPeersEvenWhenFullyQuiesced", testRatchetingGoawayForBothPeersEvenWhenFullyQuiesced),
                ("testClientTrailersMustHaveEndStreamSet", testClientTrailersMustHaveEndStreamSet),
                ("testServerTrailersMustHaveEndStreamSet", testServerTrailersMustHaveEndStreamSet),
                ("testRejectHeadersWithUppercaseHeaderFieldName", testRejectHeadersWithUppercaseHeaderFieldName),
                ("testAllowHeadersWithUppercaseHeaderFieldNameWhenValidationDisabled", testAllowHeadersWithUppercaseHeaderFieldNameWhenValidationDisabled),
                ("testRejectPseudoHeadersAfterRegularHeaders", testRejectPseudoHeadersAfterRegularHeaders),
                ("testAllowPseudoHeadersAfterRegularHeaders", testAllowPseudoHeadersAfterRegularHeaders),
                ("testRejectRequestHeadersWithMissingMethodField", testRejectRequestHeadersWithMissingMethodField),
                ("testAllowRequestHeadersWithMissingMethodFieldWhenValidationDisabled", testAllowRequestHeadersWithMissingMethodFieldWhenValidationDisabled),
                ("testRejectRequestHeadersWithMissingPathField", testRejectRequestHeadersWithMissingPathField),
                ("testAllowRequestHeadersWithMissingPathFieldWhenValidationDisabled", testAllowRequestHeadersWithMissingPathFieldWhenValidationDisabled),
                ("testRejectRequestHeadersWithEmptyPathField", testRejectRequestHeadersWithEmptyPathField),
                ("testAllowRequestHeadersWithEmptyPathFieldWhenValidationDisabled", testAllowRequestHeadersWithEmptyPathFieldWhenValidationDisabled),
                ("testRejectRequestHeadersWithMissingSchemeField", testRejectRequestHeadersWithMissingSchemeField),
                ("testAllowRequestHeadersWithMissingSchemeFieldWhenValidationDisabled", testAllowRequestHeadersWithMissingSchemeFieldWhenValidationDisabled),
                ("testRejectRequestHeadersWithDuplicateMethodField", testRejectRequestHeadersWithDuplicateMethodField),
                ("testAllowRequestHeadersWithDuplicateMethodFieldWhenValidationDisabled", testAllowRequestHeadersWithDuplicateMethodFieldWhenValidationDisabled),
                ("testRejectRequestHeadersWithDuplicatePathField", testRejectRequestHeadersWithDuplicatePathField),
                ("testAllowRequestHeadersWithDuplicatePathFieldWhenValidationDisabled", testAllowRequestHeadersWithDuplicatePathFieldWhenValidationDisabled),
                ("testRejectRequestHeadersWithDuplicateSchemeField", testRejectRequestHeadersWithDuplicateSchemeField),
                ("testAllowRequestHeadersWithDuplicateSchemeFieldWhenValidationDisabled", testAllowRequestHeadersWithDuplicateSchemeFieldWhenValidationDisabled),
                ("testRejectResponseHeadersWithMissingStatusField", testRejectResponseHeadersWithMissingStatusField),
                ("testAllowResponseHeadersWithMissingStatusFieldWhenValidationDisabled", testAllowResponseHeadersWithMissingStatusFieldWhenValidationDisabled),
                ("testRejectResponseHeadersWithDuplicateStatusField", testRejectResponseHeadersWithDuplicateStatusField),
                ("testAllowResponseHeadersWithDuplicateStatusFieldWhenValidationDisabled", testAllowResponseHeadersWithDuplicateStatusFieldWhenValidationDisabled),
                ("testRejectTrailersHeadersWithAnyPseudoHeader", testRejectTrailersHeadersWithAnyPseudoHeader),
                ("testRejectRequestHeadersWithSchemeFieldOnCONNECT", testRejectRequestHeadersWithSchemeFieldOnCONNECT),
                ("testAllowRequestHeadersWithSchemeFieldOnCONNECTValidationDisabled", testAllowRequestHeadersWithSchemeFieldOnCONNECTValidationDisabled),
                ("testRejectRequestHeadersWithPathFieldOnCONNECT", testRejectRequestHeadersWithPathFieldOnCONNECT),
                ("testAllowRequestHeadersWithPathFieldOnCONNECTValidationDisabled", testAllowRequestHeadersWithPathFieldOnCONNECTValidationDisabled),
                ("testAllowSimpleConnectRequest", testAllowSimpleConnectRequest),
                ("testRejectRequestHeadersWithoutAuthorityFieldOnCONNECT", testRejectRequestHeadersWithoutAuthorityFieldOnCONNECT),
                ("testAllowRequestHeadersWithoutAuthorityFieldOnCONNECTValidationDisabled", testAllowRequestHeadersWithoutAuthorityFieldOnCONNECTValidationDisabled),
                ("testRejectHeadersWithConnectionHeader", testRejectHeadersWithConnectionHeader),
                ("testAllowHeadersWithConnectionHeaderWhenValidationDisabled", testAllowHeadersWithConnectionHeaderWhenValidationDisabled),
                ("testRejectHeadersWithTransferEncodingHeader", testRejectHeadersWithTransferEncodingHeader),
                ("testAllowHeadersWithTransferEncodingHeaderWhenValidationDisabled", testAllowHeadersWithTransferEncodingHeaderWhenValidationDisabled),
                ("testRejectHeadersWithProxyConnectionHeader", testRejectHeadersWithProxyConnectionHeader),
                ("testAllowHeadersWithProxyConnectionHeaderWhenValidationDisabled", testAllowHeadersWithProxyConnectionHeaderWhenValidationDisabled),
                ("testRejectHeadersWithTEHeaderNotTrailers", testRejectHeadersWithTEHeaderNotTrailers),
                ("testAllowHeadersWithTEHeaderNotTrailersWhenValidationDisabled", testAllowHeadersWithTEHeaderNotTrailersWhenValidationDisabled),
                ("testAllowHeadersWithTEHeaderSetToTrailers", testAllowHeadersWithTEHeaderSetToTrailers),
                ("testSettingActualMaxFrameSize", testSettingActualMaxFrameSize),
                ("testSettingActualInitialWindowSize", testSettingActualInitialWindowSize),
                ("testPolicingExceedingContentLengthForRequests", testPolicingExceedingContentLengthForRequests),
                ("testPolicingExceedingContentLengthForResponses", testPolicingExceedingContentLengthForResponses),
                ("testPolicingMissingContentLengthForRequests", testPolicingMissingContentLengthForRequests),
                ("testPolicingMissingContentLengthForResponses", testPolicingMissingContentLengthForResponses),
                ("testPolicingInvalidContentLengthForRequestsWithEndStream", testPolicingInvalidContentLengthForRequestsWithEndStream),
                ("testPolicingInvalidContentLengthForResponsesWithEndStream", testPolicingInvalidContentLengthForResponsesWithEndStream),
                ("testValidContentLengthForRequestsWithEndStream", testValidContentLengthForRequestsWithEndStream),
                ("testValidContentLengthForResponsesWithEndStream", testValidContentLengthForResponsesWithEndStream),
                ("testNoPolicingExceedingContentLengthForRequestsWhenValidationDisabled", testNoPolicingExceedingContentLengthForRequestsWhenValidationDisabled),
                ("testNoPolicingExceedingContentLengthForResponsesWhenValidationDisabled", testNoPolicingExceedingContentLengthForResponsesWhenValidationDisabled),
                ("testNoPolicingMissingContentLengthForRequestsWhenValidationDisabled", testNoPolicingMissingContentLengthForRequestsWhenValidationDisabled),
                ("testNoPolicingMissingContentLengthForResponsesWhenValidationDisabled", testNoPolicingMissingContentLengthForResponsesWhenValidationDisabled),
                ("testNoPolicingInvalidContentLengthForRequestsWithEndStreamWhenValidationDisabled", testNoPolicingInvalidContentLengthForRequestsWithEndStreamWhenValidationDisabled),
                ("testNoPolicingInvalidContentLengthForResponsesWithEndStreamWhenValidationDisabled", testNoPolicingInvalidContentLengthForResponsesWithEndStreamWhenValidationDisabled),
                ("testWeTolerateOneStreamBeingResetTwice", testWeTolerateOneStreamBeingResetTwice),
           ]
   }
}

