//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// FlowControlHandlerTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension FlowControlHandlerTests {

   static var allTests : [(String, (FlowControlHandlerTests) -> () throws -> Void)] {
      return [
                ("testJustLettingDataThrough", testJustLettingDataThrough),
                ("testSimpleFramesKeepBoundaries", testSimpleFramesKeepBoundaries),
                ("testOverlargeFramesAreSplitByteBuffer", testOverlargeFramesAreSplitByteBuffer),
                ("testOverlargeFramesAreSplitFileRegion", testOverlargeFramesAreSplitFileRegion),
                ("testIgnoresNonDataFramesForStream", testIgnoresNonDataFramesForStream),
                ("testProperlyDelaysENDSTREAMFlag", testProperlyDelaysENDSTREAMFlag),
                ("testInterlacingWithHeaders", testInterlacingWithHeaders),
                ("testBufferedDataAndHeadersAreCancelledOnStreamClosure", testBufferedDataAndHeadersAreCancelledOnStreamClosure),
                ("testWritesForUnknownStreamsFail", testWritesForUnknownStreamsFail),
                ("testOverlargeFramesAreSplitOnMaxFrameSizeByteBuffer", testOverlargeFramesAreSplitOnMaxFrameSizeByteBuffer),
                ("testOverlargeFramesAreSplitOnMaxFrameSizeFileRegion", testOverlargeFramesAreSplitOnMaxFrameSizeFileRegion),
           ]
   }
}

