//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// HTTP2FrameParserTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension HTTP2FrameParserTests {

   @available(*, deprecated, message: "not actually deprecated. Just deprecated to allow deprecated tests (which test deprecated functionality) without warnings")
   static var allTests : [(String, (HTTP2FrameParserTests) -> () throws -> Void)] {
      return [
                ("testPaddingIsNotAllowedByEncoder", testPaddingIsNotAllowedByEncoder),
                ("testDataFrameDecodingNoPadding", testDataFrameDecodingNoPadding),
                ("testDataFrameDecodingWithPadding", testDataFrameDecodingWithPadding),
                ("testDataFrameDecodingWithPaddingSplitOverBuffers", testDataFrameDecodingWithPaddingSplitOverBuffers),
                ("testSyntheticMultipleDataFrames", testSyntheticMultipleDataFrames),
                ("testComplexPaddedSyntheticMultiDataFrames", testComplexPaddedSyntheticMultiDataFrames),
                ("testDataFrameDecodingMultibyteLength", testDataFrameDecodingMultibyteLength),
                ("testDataFrameDecodingZeroLengthPayload", testDataFrameDecodingZeroLengthPayload),
                ("testDataFrameDecodingZeroLengthPaddingOnlyPayload", testDataFrameDecodingZeroLengthPaddingOnlyPayload),
                ("testDataFrameDecodingPaddingOnlyPayload", testDataFrameDecodingPaddingOnlyPayload),
                ("testDataFrameDecodingWithOnlyPaddingSplitOverBuffers", testDataFrameDecodingWithOnlyPaddingSplitOverBuffers),
                ("testDataFrameEncoding", testDataFrameEncoding),
                ("testDataFrameEncodingMultibyteLength", testDataFrameEncodingMultibyteLength),
                ("testDataFrameEncodingViolatingMaxFrameSize", testDataFrameEncodingViolatingMaxFrameSize),
                ("testDataFrameDecodeFailureRootStream", testDataFrameDecodeFailureRootStream),
                ("testDataFrameDecodeFailureExcessPadding", testDataFrameDecodeFailureExcessPadding),
                ("testDataFrameDecodeFailureZeroLengthPayloadAndPaddedFlag", testDataFrameDecodeFailureZeroLengthPayloadAndPaddedFlag),
                ("testDataFrameDecodingViolatingMaxFrameSize", testDataFrameDecodingViolatingMaxFrameSize),
                ("testDataFrameDecodingWithOnlyPaddingSplitOverBuffersFollowedByAnotherFrame", testDataFrameDecodingWithOnlyPaddingSplitOverBuffersFollowedByAnotherFrame),
                ("testHeadersFrameDecodingNoPriorityNoPadding", testHeadersFrameDecodingNoPriorityNoPadding),
                ("testHeadersFrameDecodingNoPriorityWithPadding", testHeadersFrameDecodingNoPriorityWithPadding),
                ("testHeadersFrameDecodingWithPriorityNoPadding", testHeadersFrameDecodingWithPriorityNoPadding),
                ("testHeadersFrameDecodingWithPriorityWithPadding", testHeadersFrameDecodingWithPriorityWithPadding),
                ("testHeadersFrameDecodeFailures", testHeadersFrameDecodeFailures),
                ("testHeadersFrameDecodingWithPriorityAndIncorrectLength", testHeadersFrameDecodingWithPriorityAndIncorrectLength),
                ("testHeadersFrameDecodingWithPriorityAndCorrectLength", testHeadersFrameDecodingWithPriorityAndCorrectLength),
                ("testHeadersFrameDecodingWithZeroLengthPaddingOnly", testHeadersFrameDecodingWithZeroLengthPaddingOnly),
                ("testHeadersAndContinuationFrameDecodingWithZeroLengthPaddingOnly", testHeadersAndContinuationFrameDecodingWithZeroLengthPaddingOnly),
                ("testHeadersFrameDecodingWithZeroLengthAndPaddingFlagSet", testHeadersFrameDecodingWithZeroLengthAndPaddingFlagSet),
                ("testHeadersFrameDecodingWithNotEnoughPaddingBytes", testHeadersFrameDecodingWithNotEnoughPaddingBytes),
                ("testHeadersFrameEncodingNoPriority", testHeadersFrameEncodingNoPriority),
                ("testHeadersFrameEncodingWithPriority", testHeadersFrameEncodingWithPriority),
                ("testPriorityFrameDecoding", testPriorityFrameDecoding),
                ("testPriorityFrameDecodingFailure", testPriorityFrameDecodingFailure),
                ("testPriorityFrameEncoding", testPriorityFrameEncoding),
                ("testResetStreamFrameDecoding", testResetStreamFrameDecoding),
                ("testResetStreamFrameDecodingFailure", testResetStreamFrameDecodingFailure),
                ("testResetStreamFrameEncoding", testResetStreamFrameEncoding),
                ("testSettingsFrameDecoding", testSettingsFrameDecoding),
                ("testSettingsFrameDecodingWithNoSettings", testSettingsFrameDecodingWithNoSettings),
                ("testSettingsFrameDecodingWithUnknownItems", testSettingsFrameDecodingWithUnknownItems),
                ("testSettingsFrameDecodingFailure", testSettingsFrameDecodingFailure),
                ("testSettingsFrameEncoding", testSettingsFrameEncoding),
                ("testSettingsAckFrameDecoding", testSettingsAckFrameDecoding),
                ("testSettingsAckFrameDecodingFailure", testSettingsAckFrameDecodingFailure),
                ("testSettingsAckFrameEncoding", testSettingsAckFrameEncoding),
                ("testPushPromiseFrameDecodingNoPadding", testPushPromiseFrameDecodingNoPadding),
                ("testPushPromiseFrameDecodingWithPadding", testPushPromiseFrameDecodingWithPadding),
                ("testPushPromiseFrameDecodingFailure", testPushPromiseFrameDecodingFailure),
                ("testPushPromiseFrameEncoding", testPushPromiseFrameEncoding),
                ("testPushPromiseFrameDecodingWithZeroLengthPadding", testPushPromiseFrameDecodingWithZeroLengthPadding),
                ("testPushPromiseAndContinuationFrameDecodingWithZeroLengthPaddingOnly", testPushPromiseAndContinuationFrameDecodingWithZeroLengthPaddingOnly),
                ("testPushPromiseFrameDecodingWithZeroLengthAndPaddingFlagSet", testPushPromiseFrameDecodingWithZeroLengthAndPaddingFlagSet),
                ("testPushPromiseFrameDecodingWithNotEnoughPaddingBytes", testPushPromiseFrameDecodingWithNotEnoughPaddingBytes),
                ("testPingFrameDecoding", testPingFrameDecoding),
                ("testPingAckFrameDecoding", testPingAckFrameDecoding),
                ("testPingFrameDecodingFailure", testPingFrameDecodingFailure),
                ("testPingFrameEncoding", testPingFrameEncoding),
                ("testPingAckFrameEncoding", testPingAckFrameEncoding),
                ("testGoAwayFrameDecoding", testGoAwayFrameDecoding),
                ("testGoAwayFrameDecodingFailure", testGoAwayFrameDecodingFailure),
                ("testGoAwayFrameEncodingWithOpaqueData", testGoAwayFrameEncodingWithOpaqueData),
                ("testGoAwayFrameEncodingWithNoOpaqueData", testGoAwayFrameEncodingWithNoOpaqueData),
                ("testWindowUpdateFrameDecoding", testWindowUpdateFrameDecoding),
                ("testWindowUpdateFrameDecodingFailure", testWindowUpdateFrameDecodingFailure),
                ("testWindowUpdateFrameEncoding", testWindowUpdateFrameEncoding),
                ("testHeadersContinuationFrameDecoding", testHeadersContinuationFrameDecoding),
                ("testPushPromiseContinuationFrameDecoding", testPushPromiseContinuationFrameDecoding),
                ("testUnsolicitedContinuationFrame", testUnsolicitedContinuationFrame),
                ("testContinuationFrameStreamZero", testContinuationFrameStreamZero),
                ("testContinuationFrameWrongStream", testContinuationFrameWrongStream),
                ("testHeadersContinuationFrameDecodingWithPadding", testHeadersContinuationFrameDecodingWithPadding),
                ("testPushPromiseContinuationFrameDecodingWithPadding", testPushPromiseContinuationFrameDecodingWithPadding),
                ("testAltServiceFrameDecoding", testAltServiceFrameDecoding),
                ("testAltServiceFrameDecodingFailure", testAltServiceFrameDecodingFailure),
                ("testAltServiceFrameEncoding", testAltServiceFrameEncoding),
                ("testAltServiceFrameDecodingLengthTooShort", testAltServiceFrameDecodingLengthTooShort),
                ("testOriginFrameDecoding", testOriginFrameDecoding),
                ("testOriginFrameDecodingFailure", testOriginFrameDecodingFailure),
                ("testOriginFrameEncoding", testOriginFrameEncoding),
                ("testHeaderAndContinuationsInOneBuffer", testHeaderAndContinuationsInOneBuffer),
                ("testPushPromiseAndContinuationsInOneBuffer", testPushPromiseAndContinuationsInOneBuffer),
                ("testMultipleFramesInOneBuffer", testMultipleFramesInOneBuffer),
                ("testCorrectlyAccountForFlowControlledLength", testCorrectlyAccountForFlowControlledLength),
                ("testIgnoreGreaseFrames", testIgnoreGreaseFrames),
           ]
   }
}

