//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// HTTP2InlineStreamMultiplexerTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension HTTP2InlineStreamMultiplexerTests {

   @available(*, deprecated, message: "not actually deprecated. Just deprecated to allow deprecated tests (which test deprecated functionality) without warnings")
   static var allTests : [(String, (HTTP2InlineStreamMultiplexerTests) -> () throws -> Void)] {
      return [
                ("testMultiplexerIgnoresFramesOnStream0", testMultiplexerIgnoresFramesOnStream0),
                ("testHeadersFramesCreateNewChannels", testHeadersFramesCreateNewChannels),
                ("testChannelsCloseThemselvesWhenToldTo", testChannelsCloseThemselvesWhenToldTo),
                ("testChannelsCloseAfterResetStreamFrameFirstThenEvent", testChannelsCloseAfterResetStreamFrameFirstThenEvent),
                ("testChannelsCloseAfterGoawayFrameFirstThenEvent", testChannelsCloseAfterGoawayFrameFirstThenEvent),
                ("testClosingIdleChannels", testClosingIdleChannels),
                ("testClosingActiveChannels", testClosingActiveChannels),
                ("testClosePromiseIsSatisfied", testClosePromiseIsSatisfied),
                ("testMultipleClosePromisesAreSatisfied", testMultipleClosePromisesAreSatisfied),
                ("testClosePromiseFailsWithError", testClosePromiseFailsWithError),
                ("testFramesAreNotDeliveredUntilStreamIsSetUp", testFramesAreNotDeliveredUntilStreamIsSetUp),
                ("testFramesAreNotDeliveredIfSetUpFails", testFramesAreNotDeliveredIfSetUpFails),
                ("testFlushingOneChannelDoesntFlushThemAll", testFlushingOneChannelDoesntFlushThemAll),
                ("testUnflushedWritesFailOnError", testUnflushedWritesFailOnError),
                ("testWritesFailOnClosedStreamChannels", testWritesFailOnClosedStreamChannels),
                ("testReadPullsInAllFrames", testReadPullsInAllFrames),
                ("testReadIsPerChannel", testReadIsPerChannel),
                ("testReadWillCauseAutomaticFrameDelivery", testReadWillCauseAutomaticFrameDelivery),
                ("testReadWithNoPendingDataCausesReadOnParentChannel", testReadWithNoPendingDataCausesReadOnParentChannel),
                ("testHandlersAreRemovedOnClosure", testHandlersAreRemovedOnClosure),
                ("testHandlersAreRemovedOnClosureWithError", testHandlersAreRemovedOnClosureWithError),
                ("testCreatingOutboundChannelClient", testCreatingOutboundChannelClient),
                ("testWritesOnCreatedChannelAreDelayed", testWritesOnCreatedChannelAreDelayed),
                ("testWritesAreCancelledOnFailingInitializer", testWritesAreCancelledOnFailingInitializer),
                ("testFailingInitializerDoesNotWrite", testFailingInitializerDoesNotWrite),
                ("testCreatedChildChannelDoesNotActivateEarly", testCreatedChildChannelDoesNotActivateEarly),
                ("testCreatedChildChannelActivatesIfParentIsActive", testCreatedChildChannelActivatesIfParentIsActive),
                ("testInitiatedChildChannelActivates", testInitiatedChildChannelActivates),
                ("testMultiplexerIgnoresPriorityFrames", testMultiplexerIgnoresPriorityFrames),
                ("testMultiplexerForwardsActiveToParent", testMultiplexerForwardsActiveToParent),
                ("testCreatedChildChannelCanBeClosedImmediately", testCreatedChildChannelCanBeClosedImmediately),
                ("testCreatedChildChannelCanBeClosedBeforeWritingHeaders", testCreatedChildChannelCanBeClosedBeforeWritingHeaders),
                ("testCreatedChildChannelCanBeClosedImmediatelyWhenBaseIsActive", testCreatedChildChannelCanBeClosedImmediatelyWhenBaseIsActive),
                ("testCreatedChildChannelCanBeClosedBeforeWritingHeadersWhenBaseIsActive", testCreatedChildChannelCanBeClosedBeforeWritingHeadersWhenBaseIsActive),
                ("testMultiplexerCoalescesFlushCallsDuringChannelRead", testMultiplexerCoalescesFlushCallsDuringChannelRead),
                ("testMultiplexerDoesntFireReadCompleteForEachFrame", testMultiplexerDoesntFireReadCompleteForEachFrame),
                ("testMultiplexerCorrectlyTellsAllStreamsAboutReadComplete", testMultiplexerCorrectlyTellsAllStreamsAboutReadComplete),
                ("testMultiplexerModifiesStreamChannelWritabilityBasedOnFixedSizeTokens", testMultiplexerModifiesStreamChannelWritabilityBasedOnFixedSizeTokens),
                ("testMultiplexerModifiesStreamChannelWritabilityBasedOnParentChannelWritability", testMultiplexerModifiesStreamChannelWritabilityBasedOnParentChannelWritability),
                ("testMultiplexerModifiesStreamChannelWritabilityBasedOnFixedSizeTokensAndChannelWritability", testMultiplexerModifiesStreamChannelWritabilityBasedOnFixedSizeTokensAndChannelWritability),
                ("testStreamChannelToleratesFailingInitializer", testStreamChannelToleratesFailingInitializer),
                ("testReadWhenUsingAutoreadOnChildChannel", testReadWhenUsingAutoreadOnChildChannel),
                ("testStreamChannelSupportsSyncOptions", testStreamChannelSupportsSyncOptions),
                ("testStreamErrorIsDeliveredToChannel", testStreamErrorIsDeliveredToChannel),
                ("testPendingReadsAreFlushedEvenWithoutUnsatisfiedReadOnChannelInactive", testPendingReadsAreFlushedEvenWithoutUnsatisfiedReadOnChannelInactive),
           ]
   }
}

