//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// SimpleClientServerFramePayloadStreamTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension SimpleClientServerFramePayloadStreamTests {

   @available(*, deprecated, message: "not actually deprecated. Just deprecated to allow deprecated tests (which test deprecated functionality) without warnings")
   static var allTests : [(String, (SimpleClientServerFramePayloadStreamTests) -> () throws -> Void)] {
      return [
                ("testBasicRequestResponse", testBasicRequestResponse),
                ("testBasicRequestResponseWithDynamicPipeline", testBasicRequestResponseWithDynamicPipeline),
                ("testManyRequestsAtOnce", testManyRequestsAtOnce),
                ("testNothingButGoaway", testNothingButGoaway),
                ("testGoAwayWithStreamsUpQuiescing", testGoAwayWithStreamsUpQuiescing),
                ("testLargeDataFramesAreSplit", testLargeDataFramesAreSplit),
                ("testSendingDataFrameWithSmallFile", testSendingDataFrameWithSmallFile),
                ("testSendingDataFrameWithLargeFile", testSendingDataFrameWithLargeFile),
                ("testMoreRequestsThanMaxConcurrentStreamsAtOnce", testMoreRequestsThanMaxConcurrentStreamsAtOnce),
                ("testOverridingDefaultSettings", testOverridingDefaultSettings),
                ("testBasicPingFrames", testBasicPingFrames),
                ("testAutomaticFlowControl", testAutomaticFlowControl),
                ("testPartialFrame", testPartialFrame),
                ("testSendingTrailers", testSendingTrailers),
                ("test1XXResponseHeaderFields", test1XXResponseHeaderFields),
                ("testPriorityFrames", testPriorityFrames),
                ("testStreamClosedWithNoError", testStreamClosedWithNoError),
                ("testStreamClosedViaRstStream", testStreamClosedViaRstStream),
                ("testStreamClosedViaGoaway", testStreamClosedViaGoaway),
                ("testStreamCloseEventForRstStreamFiresAfterFrame", testStreamCloseEventForRstStreamFiresAfterFrame),
                ("testStreamCloseEventForGoawayFiresAfterFrame", testStreamCloseEventForGoawayFiresAfterFrame),
                ("testManyConcurrentInactiveStreams", testManyConcurrentInactiveStreams),
                ("testBadClientMagic", testBadClientMagic),
                ("testOpeningWindowsViaSettingsInitialWindowSize", testOpeningWindowsViaSettingsInitialWindowSize),
                ("testSettingsAckNotifiesAboutChangedFlowControl", testSettingsAckNotifiesAboutChangedFlowControl),
                ("testStreamMultiplexerAcknowledgesSettingsBasedFlowControlChanges", testStreamMultiplexerAcknowledgesSettingsBasedFlowControlChanges),
                ("testChangingMaxFrameSize", testChangingMaxFrameSize),
                ("testStreamErrorOnSelfDependentPriorityFrames", testStreamErrorOnSelfDependentPriorityFrames),
                ("testStreamErrorOnSelfDependentHeadersFrames", testStreamErrorOnSelfDependentHeadersFrames),
                ("testInvalidRequestHeaderBlockAllowsRstStream", testInvalidRequestHeaderBlockAllowsRstStream),
                ("testClientConnectionErrorCorrectlyReported", testClientConnectionErrorCorrectlyReported),
                ("testChangingMaxConcurrentStreams", testChangingMaxConcurrentStreams),
                ("testFailsPromisesForBufferedWrites", testFailsPromisesForBufferedWrites),
                ("testAllowPushPromiseBeforeReceivingHeadersNoBody", testAllowPushPromiseBeforeReceivingHeadersNoBody),
                ("testAllowPushPromiseBeforeReceivingHeadersWithPossibleBody", testAllowPushPromiseBeforeReceivingHeadersWithPossibleBody),
                ("testSequentialEmptyDataFramesIsForbidden", testSequentialEmptyDataFramesIsForbidden),
                ("testSequentialEmptyDataFramesLimitIsConfigurable", testSequentialEmptyDataFramesLimitIsConfigurable),
                ("testDenialOfServiceViaPing", testDenialOfServiceViaPing),
                ("testDenialOfServiceViaSettings", testDenialOfServiceViaSettings),
                ("testFramesArentWrittenWhenChannelIsntWritable", testFramesArentWrittenWhenChannelIsntWritable),
                ("testEnforcingMaxHeaderListSize", testEnforcingMaxHeaderListSize),
                ("testForbidsExceedingMaxHeaderListSizeBeforeDecoding", testForbidsExceedingMaxHeaderListSizeBeforeDecoding),
                ("testForbidsExceedingMaxHeaderListSizeBeforeDecodingSingleFrame", testForbidsExceedingMaxHeaderListSizeBeforeDecodingSingleFrame),
                ("testNoStreamWindowUpdateOnEndStreamFrameFromServer", testNoStreamWindowUpdateOnEndStreamFrameFromServer),
                ("testNoStreamWindowUpdateOnEndStreamFrameFromClient", testNoStreamWindowUpdateOnEndStreamFrameFromClient),
                ("testGreasedSettingsAreTolerated", testGreasedSettingsAreTolerated),
                ("testStreamCreationOrder", testStreamCreationOrder),
           ]
   }
}

