//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// SimpleClientServerTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension SimpleClientServerTests {

   static var allTests : [(String, (SimpleClientServerTests) -> () throws -> Void)] {
      return [
                ("testBasicRequestResponse", testBasicRequestResponse),
                ("testBasicRequestResponseWithDynamicPipeline", testBasicRequestResponseWithDynamicPipeline),
                ("testManyRequestsAtOnce", testManyRequestsAtOnce),
                ("testNothingButGoaway", testNothingButGoaway),
                ("testGoAwayWithStreamsUpQuiescing", testGoAwayWithStreamsUpQuiescing),
                ("testLargeDataFramesAreSplit", testLargeDataFramesAreSplit),
                ("testSendingDataFrameWithSmallFile", testSendingDataFrameWithSmallFile),
                ("testSendingDataFrameWithLargeFile", testSendingDataFrameWithLargeFile),
                ("testMoreRequestsThanMaxConcurrentStreamsAtOnce", testMoreRequestsThanMaxConcurrentStreamsAtOnce),
                ("testOverridingDefaultSettings", testOverridingDefaultSettings),
                ("testBasicPingFrames", testBasicPingFrames),
                ("testAutomaticFlowControl", testAutomaticFlowControl),
                ("testPartialFrame", testPartialFrame),
                ("testSendingTrailers", testSendingTrailers),
                ("test1XXResponseHeaderFields", test1XXResponseHeaderFields),
                ("testPriorityFrames", testPriorityFrames),
                ("testStreamClosedWithNoError", testStreamClosedWithNoError),
                ("testStreamClosedViaRstStream", testStreamClosedViaRstStream),
                ("testStreamClosedViaGoaway", testStreamClosedViaGoaway),
                ("testStreamCloseEventForRstStreamFiresAfterFrame", testStreamCloseEventForRstStreamFiresAfterFrame),
                ("testStreamCloseEventForGoawayFiresAfterFrame", testStreamCloseEventForGoawayFiresAfterFrame),
                ("testManyConcurrentInactiveStreams", testManyConcurrentInactiveStreams),
                ("testBadClientMagic", testBadClientMagic),
                ("testOpeningWindowsViaSettingsInitialWindowSize", testOpeningWindowsViaSettingsInitialWindowSize),
                ("testSettingsAckNotifiesAboutChangedFlowControl", testSettingsAckNotifiesAboutChangedFlowControl),
                ("testStreamMultiplexerAcknowledgesSettingsBasedFlowControlChanges", testStreamMultiplexerAcknowledgesSettingsBasedFlowControlChanges),
                ("testChangingMaxFrameSize", testChangingMaxFrameSize),
                ("testStreamErrorOnSelfDependentPriorityFrames", testStreamErrorOnSelfDependentPriorityFrames),
                ("testStreamErrorOnSelfDependentHeadersFrames", testStreamErrorOnSelfDependentHeadersFrames),
                ("testInvalidRequestHeaderBlockAllowsRstStream", testInvalidRequestHeaderBlockAllowsRstStream),
           ]
   }
}

