//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftNIO open source project
//
// Copyright (c) 2017-2018 Apple Inc. and the SwiftNIO project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftNIO project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// SimpleClientServerTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension SimpleClientServerTests {

   static var allTests : [(String, (SimpleClientServerTests) -> () throws -> Void)] {
      return [
                ("testBasicRequestResponse", testBasicRequestResponse),
                ("testBasicRequestResponseWithDynamicPipeline", testBasicRequestResponseWithDynamicPipeline),
                ("testManyRequestsAtOnce", testManyRequestsAtOnce),
                ("testNothingButGoaway", testNothingButGoaway),
                ("testGoAwayWithStreamsUpQuiescing", testGoAwayWithStreamsUpQuiescing),
                ("testLargeDataFramesAreSplit", testLargeDataFramesAreSplit),
                ("testSendingDataFrameWithSmallFile", testSendingDataFrameWithSmallFile),
                ("testSendingDataFrameWithLargeFile", testSendingDataFrameWithLargeFile),
                ("testMoreRequestsThanMaxConcurrentStreamsAtOnce", testMoreRequestsThanMaxConcurrentStreamsAtOnce),
                ("testOverridingDefaultSettings", testOverridingDefaultSettings),
                ("testBasicPingFrames", testBasicPingFrames),
                ("testUnflushedWritesAreFailedOnChannelInactive", testUnflushedWritesAreFailedOnChannelInactive),
                ("testUnflushedWritesAreFailedOnHalfClosure", testUnflushedWritesAreFailedOnHalfClosure),
                ("testUnflushedWritesAreFailedOnChannelInactiveRentrant", testUnflushedWritesAreFailedOnChannelInactiveRentrant),
                ("testUnflushedWritesAreFailedOnHalfClosureReentrant", testUnflushedWritesAreFailedOnHalfClosureReentrant),
                ("testFrameReceivesDoNotTriggerFlushes", testFrameReceivesDoNotTriggerFlushes),
                ("testAutomaticFlowControl", testAutomaticFlowControl),
                ("testPartialFrame", testPartialFrame),
                ("testFailingUnflushedWritesForResetStream", testFailingUnflushedWritesForResetStream),
                ("testFailingFlushedWritesForResetStream", testFailingFlushedWritesForResetStream),
                ("testFailingUnflushedWritesForGoaway", testFailingUnflushedWritesForGoaway),
                ("testFailingFlushedWritesForGoaway", testFailingFlushedWritesForGoaway),
                ("testSendingTrailers", testSendingTrailers),
                ("testSendingTrailersWhenDataProviderIsIdle", testSendingTrailersWhenDataProviderIsIdle),
                ("test1XXResponseHeaderFields", test1XXResponseHeaderFields),
                ("testPriorityFramesAreNotEmitted", testPriorityFramesAreNotEmitted),
                ("testStreamClosedWithNoError", testStreamClosedWithNoError),
                ("testStreamClosedViaRstStream", testStreamClosedViaRstStream),
                ("testStreamClosedViaGoaway", testStreamClosedViaGoaway),
                ("testStreamCloseEventForRstStreamFiresAfterFrame", testStreamCloseEventForRstStreamFiresAfterFrame),
                ("testStreamCloseEventForGoawayFiresAfterFrame", testStreamCloseEventForGoawayFiresAfterFrame),
                ("testManyConcurrentInactiveStreams", testManyConcurrentInactiveStreams),
                ("testDontRemoveActiveStreams", testDontRemoveActiveStreams),
                ("testCachingInteractionWithMaxConcurrentStreams", testCachingInteractionWithMaxConcurrentStreams),
                ("testBadClientMagic", testBadClientMagic),
           ]
   }
}

