version: "3"

services:

  runtime-setup:
    image: swift-nio-http2:16.04-5.2
    build:
      args:
        ubuntu_version: "xenial"
        swift_version: "5.2"
        h2spec_version: "2.2.1"

  unit-tests:
    image: swift-nio-http2:16.04-5.2

  integration-tests:
    image: swift-nio-http2:16.04-5.2

  performance-test:
    image: swift-nio-http2:16.04-5.2

  h2spec:
    image: swift-nio-http2:16.04-5.2

  test:
    image: swift-nio-http2:16.04-5.2
    environment:
      - MAX_ALLOCS_ALLOWED_1k_requests_interleaved=51150
      - MAX_ALLOCS_ALLOWED_1k_requests_noninterleaved=50100
      - MAX_ALLOCS_ALLOWED_client_server_h1_request_response=325000
      - MAX_ALLOCS_ALLOWED_client_server_request_response=289000
      - MAX_ALLOCS_ALLOWED_create_client_stream_channel=48050
      - MAX_ALLOCS_ALLOWED_hpack_decoding=5050
      - MAX_ALLOCS_ALLOWED_stream_teardown_100_concurrent=353200
      - SANITIZER_ARG=--sanitize=thread

  shell:
    image: swift-nio-http2:16.04-5.2
