version: "3"

services:

  runtime-setup:
    image: swift-nio-http2:20.04-5.4
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.4-focal"
        ubuntu_version: "focal"
        swift_version: "5.4"
        h2spec_version: "2.2.1"

  unit-tests:
    image: swift-nio-http2:20.04-5.4

  integration-tests:
    image: swift-nio-http2:20.04-5.4
    environment:
      - MAX_ALLOCS_ALLOWED_create_client_stream_channel=58000
      - MAX_ALLOCS_ALLOWED_hpack_decoding=5050
      - MAX_ALLOCS_ALLOWED_client_server_request_response=301000
      - MAX_ALLOCS_ALLOWED_client_server_h1_request_response=338000
      - MAX_ALLOCS_ALLOWED_1k_requests_interleaved=53000
      - MAX_ALLOCS_ALLOWED_1k_requests_noninterleaved=52000
      - MAX_ALLOCS_ALLOWED_stream_teardown_100_concurrent=364000

  performance-test:
    image: swift-nio-http2:20.04-5.4

  h2spec:
    image: swift-nio-http2:20.04-5.4

  test:
    image: swift-nio-http2:20.04-5.4
    environment:
      - MAX_ALLOCS_ALLOWED_create_client_stream_channel=58000
      - MAX_ALLOCS_ALLOWED_hpack_decoding=5050
      - MAX_ALLOCS_ALLOWED_client_server_request_response=301000
      - MAX_ALLOCS_ALLOWED_client_server_h1_request_response=338000
      - MAX_ALLOCS_ALLOWED_1k_requests_interleaved=53000
      - MAX_ALLOCS_ALLOWED_1k_requests_noninterleaved=52000
      - MAX_ALLOCS_ALLOWED_stream_teardown_100_concurrent=364000

  shell:
    image: swift-nio-http2:20.04-5.4
