version: "3"

services:

  runtime-setup:
    image: swift-nio-http2:18.04-5.3
    build:
      args:
        ubuntu_version: "bionic"
        swift_version: "5.3"
        h2spec_version: "2.2.1"

  unit-tests:
    image: swift-nio-http2:18.04-5.3

  integration-tests:
    image: swift-nio-http2:18.04-5.3
    environment:
      - MAX_ALLOCS_ALLOWED_create_client_stream_channel=63000
      - MAX_ALLOCS_ALLOWED_hpack_decoding=5050
      - MAX_ALLOCS_ALLOWED_client_server_request_response=319000
      - MAX_ALLOCS_ALLOWED_client_server_h1_request_response=366000
      - MAX_ALLOCS_ALLOWED_1k_requests_interleaved=59000
      - MAX_ALLOCS_ALLOWED_1k_requests_noninterleaved=58000
      - MAX_ALLOCS_ALLOWED_stream_teardown_100_concurrent=414000

  performance-test:
    image: swift-nio-http2:18.04-5.3

  h2spec:
    image: swift-nio-http2:18.04-5.3

  test:
    image: swift-nio-http2:18.04-5.3
    environment:
      - MAX_ALLOCS_ALLOWED_create_client_stream_channel=63000
      - MAX_ALLOCS_ALLOWED_hpack_decoding=5050
      - MAX_ALLOCS_ALLOWED_client_server_request_response=319000
      - MAX_ALLOCS_ALLOWED_client_server_h1_request_response=366000
      - MAX_ALLOCS_ALLOWED_1k_requests_interleaved=59000
      - MAX_ALLOCS_ALLOWED_1k_requests_noninterleaved=58000
      - MAX_ALLOCS_ALLOWED_stream_teardown_100_concurrent=414000

  shell:
    image: swift-nio-http2:18.04-5.3
