version: "3"

services:

  runtime-setup:
    image: swift-nio-http2:20.04-5.5
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.5"
        h2spec_version: "2.2.1"

  unit-tests:
    image: swift-nio-http2:20.04-5.5

  integration-tests:
    image: swift-nio-http2:20.04-5.5

  performance-test:
    image: swift-nio-http2:20.04-5.5

  h2spec:
    image: swift-nio-http2:20.04-5.5

  test:
    image: swift-nio-http2:20.04-5.5
    environment:
      - MAX_ALLOCS_ALLOWED_1k_requests_interleaved=49150
      - MAX_ALLOCS_ALLOWED_1k_requests_noninterleaved=48100
      - MAX_ALLOCS_ALLOWED_client_server_h1_request_response=324000
      - MAX_ALLOCS_ALLOWED_client_server_request_response=288000
      - MAX_ALLOCS_ALLOWED_create_client_stream_channel=48050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form=700050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace=700050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace_from_long_string=800050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace_from_short_string=700050
      - MAX_ALLOCS_ALLOWED_hpack_decoding=5050
      - MAX_ALLOCS_ALLOWED_stream_teardown_100_concurrent=333200

  shell:
    image: swift-nio-http2:20.04-5.5
