version: "3"

services:

  runtime-setup:
    image: swift-nio-http2:16.04-5.2
    build:
      args:
        ubuntu_version: "xenial"
        swift_version: "5.2"
        h2spec_version: "2.2.1"

  unit-tests:
    image: swift-nio-http2:16.04-5.2

  integration-tests:
    image: swift-nio-http2:16.04-5.2

  performance-test:
    image: swift-nio-http2:16.04-5.2

  h2spec:
    image: swift-nio-http2:16.04-5.2

  test:
    image: swift-nio-http2:16.04-5.2
    environment:
      - MAX_ALLOCS_ALLOWED_1k_requests_interleaved=48200
      - MAX_ALLOCS_ALLOWED_1k_requests_noninterleaved=47100
      - MAX_ALLOCS_ALLOWED_client_server_h1_request_response=310050
      - MAX_ALLOCS_ALLOWED_client_server_request_response=274050
      - MAX_ALLOCS_ALLOWED_create_client_stream_channel=42050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form=200050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace=200050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace_from_long_string=300050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace_from_short_string=200050
      - MAX_ALLOCS_ALLOWED_hpack_decoding=5050
      - MAX_ALLOCS_ALLOWED_stream_teardown_100_concurrent=323150
      - SANITIZER_ARG=--sanitize=thread

  shell:
    image: swift-nio-http2:16.04-5.2
