version: "3"

services:

  runtime-setup:
    image: swift-nio-http2:18.04-5.3
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.3-bionic"
        h2spec_version: "2.2.1"

  unit-tests:
    image: swift-nio-http2:18.04-5.3

  integration-tests:
    image: swift-nio-http2:18.04-5.3
    environment:
      - MAX_ALLOCS_ALLOWED_create_client_stream_channel=72010
      - MAX_ALLOCS_ALLOWED_hpack_decoding=5050
      - MAX_ALLOCS_ALLOWED_client_server_request_response=384810

  performance-test:
    image: swift-nio-http2:18.04-5.3

  h2spec:
    image: swift-nio-http2:18.04-5.3

  test:
    image: swift-nio-http2:18.04-5.3
    environment:
      - MAX_ALLOCS_ALLOWED_create_client_stream_channel=72010
      - MAX_ALLOCS_ALLOWED_hpack_decoding=5050
      - MAX_ALLOCS_ALLOWED_client_server_request_response=384810

  shell:
    image: swift-nio-http2:18.04-5.3
