version: "3"

services:

  runtime-setup:
    image: swift-nio-http2:ubuntu-16.04-4.0.3
    build:
      args:
        ubuntu_version : "16.04"
        swift_version : "4.0.3"
        install_nghttp2_from_source: "true"

  test:
    image: swift-nio-http2:ubuntu-16.04-4.0.3
