# this file is not designed to be run directly
# instead, use the docker-compose.<os>.<swift> files
# eg docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.1804.42.yaml run test
version: "3"

services:

  runtime-setup:
    image: swift-nio-http2:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: swift-nio-http2:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code
    working_dir: /code

  sanity:
    <<: *common
    command: /bin/bash -cl "./scripts/sanity.sh"

  unit-tests:
    <<: *common
    command: /bin/bash -cl "swift test -Xswiftc -warnings-as-errors"

  integration-tests:
    <<: *common
    command: /bin/bash -cl "./scripts/integration_tests.sh"

  h2spec:
    <<: *common
    command: /bin/bash -cl "./scripts/test_h2spec.sh"

  test:
    <<: *common
    command: /bin/bash -cl "swift test -Xswiftc -warnings-as-errors && ./scripts/integration_tests.sh && ./scripts/test_h2spec.sh"
