version: "3"

services:

  runtime-setup:
    image: swift-nio:20.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-focal"
        ubuntu_version: "focal"

  unit-tests:
    image: swift-nio:20.04-main

  integration-tests:
    image: swift-nio:20.04-main

  test:
    image: swift-nio:20.04-main
    environment:
      - MAX_ALLOCS_ALLOWED_1000_addHandlers=47050
      - MAX_ALLOCS_ALLOWED_1000_addHandlers_sync=40050
      - MAX_ALLOCS_ALLOWED_1000_getHandlers=12050
      - MAX_ALLOCS_ALLOWED_1000_getHandlers_sync=50
      - MAX_ALLOCS_ALLOWED_1000_reqs_1_conn=30540
      - MAX_ALLOCS_ALLOWED_1000_tcpbootstraps=4100
      - MAX_ALLOCS_ALLOWED_1000_tcpconnections=179010
      - MAX_ALLOCS_ALLOWED_1000_udp_reqs=16050
      - MAX_ALLOCS_ALLOWED_1000_udpbootstraps=2000
      - MAX_ALLOCS_ALLOWED_1000_udpconnections=101050
      - MAX_ALLOCS_ALLOWED_1_reqs_1000_conn=471050
      - MAX_ALLOCS_ALLOWED_bytebuffer_lots_of_rw=2100
      - MAX_ALLOCS_ALLOWED_creating_10000_headers=100
      - MAX_ALLOCS_ALLOWED_decode_1000_ws_frames=2000
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_holding_buffer=1000
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_holding_buffer_with_space=1000
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_new_buffer=5010
      - MAX_ALLOCS_ALLOWED_encode_1000_ws_frames_new_buffer_with_space=5010
      - MAX_ALLOCS_ALLOWED_future_lots_of_callbacks=75010
      - MAX_ALLOCS_ALLOWED_modifying_1000_circular_buffer_elements=50
      - MAX_ALLOCS_ALLOWED_modifying_byte_buffer_view=2010
      - MAX_ALLOCS_ALLOWED_ping_pong_1000_reqs_1_conn=4440
      - MAX_ALLOCS_ALLOWED_read_10000_chunks_from_file=190500
      - MAX_ALLOCS_ALLOWED_schedule_10000_tasks=90050
      - MAX_ALLOCS_ALLOWED_scheduling_10000_executions=20150
      - MAX_ALLOCS_ALLOWED_udp_1000_reqs_1_conn=16250
      - MAX_ALLOCS_ALLOWED_udp_1_reqs_1000_conn=202050
      - SANITIZER_ARG=--sanitize=thread

  performance-test:
    image: swift-nio:20.04-main

  shell:
    image: swift-nio:20.04-main

  echo:
    image: swift-nio:20.04-main

  http:
    image: swift-nio:20.04-main
