# this file is not designed to be run directly
# instead, use the docker-compose.<os>.<swift> files
# eg docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.1804.42.yaml run test
version: "3"

services:

  runtime-setup:
    image: swift-nio-http2:default
    build:
      context: .
      dockerfile: Dockerfile

  common: &common
    image: swift-nio-http2:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code:z
    working_dir: /code
    cap_drop:
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE

  sanity:
    <<: *common
    command: /bin/bash -cl "./scripts/sanity.sh"

  test:
    <<: *common
    command: /bin/bash -cl "swift test"
