version: "3"

services:

  runtime-setup:
    image: swift-nio-http2:22.04-5.7
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.7"
        h2spec_version: "2.2.1"

  unit-tests:
    image: swift-nio-http2:22.04-5.7

  integration-tests:
    image: swift-nio-http2:22.04-5.7

  performance-test:
    image: swift-nio-http2:22.04-5.7

  h2spec:
    image: swift-nio-http2:22.04-5.7

  test:
    image: swift-nio-http2:22.04-5.7
    environment:
      - MAX_ALLOCS_ALLOWED_1k_requests_interleaved=43200
      - MAX_ALLOCS_ALLOWED_1k_requests_noninterleaved=42100
      - MAX_ALLOCS_ALLOWED_client_server_h1_request_response=307050
      - MAX_ALLOCS_ALLOWED_client_server_request_response=273050
      - MAX_ALLOCS_ALLOWED_create_client_stream_channel=41050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form=200050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace=200050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace_from_long_string=300050
      - MAX_ALLOCS_ALLOWED_get_100000_headers_canonical_form_trimming_whitespace_from_short_string=200050
      - MAX_ALLOCS_ALLOWED_hpack_decoding=5050
      - MAX_ALLOCS_ALLOWED_stream_teardown_100_concurrent=293350

  shell:
    image: swift-nio-http2:22.04-5.7
