# this file is not designed to be run directly
# instead, use the docker-compose.<os>.<swift> files
# eg docker-compose -f docker/docker-compose.yaml -f docker/docker-compose.ubuntu-1604.41.yaml run test
version: "3"

services:

  runtime-setup:
    image: swift-nio-http2:default
    build:
      context: .
      dockerfile: Dockerfile.ubuntu

  common: &common
    image: swift-nio-http2:default
    depends_on: [runtime-setup]
    volumes:
      - ~/.ssh:/root/.ssh
      - ..:/code
    working_dir: /code

  sanity:
    <<: *common
    command: /bin/bash -cl "./scripts/sanity.sh"

  test:
    <<: *common
    command: /bin/bash -cl "swift test"
